spring:
  application:
    name: FilmForum

  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10

    # mysql服务地址 格式：jdbc:mysql://{mysql服务所在IP地址}:{mysql服务所在端口}/{数据库名称}?{一些参数}
    url: jdbc:mysql://127.0.0.1:3306/filmforum?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    # 使用的用户名
    username: root
    # 用户名对应的密码
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  autoconfigure:
    #暂时跳过security自动配置，之后鉴权完善后会去掉
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration




server:
    port: 8080